// Configuration file - Multi-region setup with failover
// Auto-generated by setup-frontend.sh on Sat Nov 29 06:44:55 -05 2025
const CONFIG = {
    // URLs de las Lambdas
    PRIMARY_API_URL: 'https://22zuzpqcp3m7xmoz3jogogkaae0uszgw.lambda-url.us-east-1.on.aws',
    SECONDARY_API_URL: 'https://tnn7m36d6s6uliwu7kjd5hivia0bztcq.lambda-url.us-west-2.on.aws',
    
    // Configuración de failover
    FAILOVER_ENABLED: true,
    HEALTH_CHECK_INTERVAL: 30000, // 30 segundos
    REQUEST_TIMEOUT: 5000, // 5 segundos
    MAX_RETRIES: 2
};
