#!/bin/bash

# Script para configurar automáticamente las URLs de Lambda en el frontend
# Uso: ./setup-frontend.sh [environment]

set -e

ENVIRONMENT=${1:-dev}
CONFIG_FILE="config.js"

echo "🔍 Obteniendo URLs de Lambda para environment: ${ENVIRONMENT}"
echo ""

# Get Lambda URLs from AWS
echo "📡 Consultando Lambda en us-east-1..."
PRIMARY_URL=$(aws lambda get-function-url-config \
    --function-name "multiregion-${ENVIRONMENT}-api" \
    --region us-east-1 \
    --query 'FunctionUrl' \
    --output text 2>/dev/null || echo "NOT_FOUND")

echo "📡 Consultando Lambda en us-west-2..."
SECONDARY_URL=$(aws lambda get-function-url-config \
    --function-name "multiregion-${ENVIRONMENT}-api-2" \
    --region us-west-2 \
    --query 'FunctionUrl' \
    --output text 2>/dev/null || echo "NOT_FOUND")

if [ "$PRIMARY_URL" == "NOT_FOUND" ] || [ "$SECONDARY_URL" == "NOT_FOUND" ]; then
    echo "❌ Error: No se pudieron obtener las URLs de Lambda"
    echo ""
    echo "Por favor, configura manualmente el archivo config.js con tus URLs:"
    echo ""
    echo "PRIMARY_API_URL: ${PRIMARY_URL}"
    echo "SECONDARY_API_URL: ${SECONDARY_URL}"
    exit 1
fi

# Remove trailing slash if exists
PRIMARY_URL=${PRIMARY_URL%/}
SECONDARY_URL=${SECONDARY_URL%/}

echo ""
echo "✅ URLs encontradas:"
echo "   Primary (us-east-1):   ${PRIMARY_URL}"
echo "   Secondary (us-west-2): ${SECONDARY_URL}"
echo ""

# Update config.js
cat > ${CONFIG_FILE} << EOF
// Configuration file - Multi-region setup with failover
// Auto-generated by setup-frontend.sh on $(date)
const CONFIG = {
    // URLs de las Lambdas
    PRIMARY_API_URL: '${PRIMARY_URL}',
    SECONDARY_API_URL: '${SECONDARY_URL}',
    
    // Configuración de failover
    FAILOVER_ENABLED: true,
    HEALTH_CHECK_INTERVAL: 30000, // 30 segundos
    REQUEST_TIMEOUT: 5000, // 5 segundos
    MAX_RETRIES: 2
};
EOF

echo "✅ Archivo config.js actualizado correctamente"
echo ""
echo "🚀 Para iniciar el frontend:"
echo "   docker-compose up -d"
echo ""
echo "🌐 Luego abre: http://localhost:8080"
echo ""

# Test the endpoints
echo "🧪 Probando conectividad..."
echo ""

test_endpoint() {
    local url=$1
    local name=$2
    
    if curl -s -o /dev/null -w "%{http_code}" --max-time 5 "${url}/health" | grep -q "200"; then
        echo "   ✅ ${name}: OK"
        return 0
    else
        echo "   ❌ ${name}: FAIL"
        return 1
    fi
}

test_endpoint "${PRIMARY_URL}" "Primary (us-east-1)"
test_endpoint "${SECONDARY_URL}" "Secondary (us-west-2)"

echo ""
echo "✨ Setup completado. ¡Listo para usar!"
